// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TipoRelacionamentosTabelas.Data;

#nullable disable

namespace TipoRelacionamentosTabelas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240325122447_CasaMoradorRelacionamento")]
    partial class CasaMoradorRelacionamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoradorModelcasaModel", b =>
                {
                    b.Property<int>("CasasId")
                        .HasColumnType("int");

                    b.Property<int>("MoradoresId")
                        .HasColumnType("int");

                    b.HasKey("CasasId", "MoradoresId");

                    b.HasIndex("MoradoresId");

                    b.ToTable("MoradorModelcasaModel");
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.MoradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Moradores");
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.casaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.moradaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CasaId")
                        .IsUnique();

                    b.ToTable("Moradas");
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.quartoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.ToTable("quartoModel");
                });

            modelBuilder.Entity("MoradorModelcasaModel", b =>
                {
                    b.HasOne("TipoRelacionamentosTabelas.Models.casaModel", null)
                        .WithMany()
                        .HasForeignKey("CasasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TipoRelacionamentosTabelas.Models.MoradorModel", null)
                        .WithMany()
                        .HasForeignKey("MoradoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.moradaModel", b =>
                {
                    b.HasOne("TipoRelacionamentosTabelas.Models.casaModel", "Casa")
                        .WithOne("Morada")
                        .HasForeignKey("TipoRelacionamentosTabelas.Models.moradaModel", "CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.quartoModel", b =>
                {
                    b.HasOne("TipoRelacionamentosTabelas.Models.casaModel", "Casa")
                        .WithMany("Quartos")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("TipoRelacionamentosTabelas.Models.casaModel", b =>
                {
                    b.Navigation("Morada")
                        .IsRequired();

                    b.Navigation("Quartos");
                });
#pragma warning restore 612, 618
        }
    }
}
